package commands.enums;

public enum CommandType {

    LOGIN,
    LOGOUT,
    CREATE_NEW_MEMBER,
    SHOW_BOARD_ACTIVITY,
    SHOW_TEAM_BOARD,
    CREATE_NEW_BOARD,
    CREATE_NEW_BUG,
    CREATE_NEW_FEEDBACK,
    CREATE_NEW_STORY,
    CREATE_NEW_TEAM,
    SHOW_ALL_TEAMS,
    SHOW_MEMBER_ACTIVITY,
    SHOW_TEAM_MEMBERS,
    ADD_MEMBER_TO_TEAM,
    SHOW_ALL_MEMBERS,
    SHOW_TEAM_ACTIVITY,
    ADD_COMMENT_TO_TASK,
    ASSIGN_BUG,
    ASSIGN_STORY,
    CHANGE_BUG,
    CHANGE_STORY,
    CHANGE_FEEDBACK,
    SORT,
    FILTER,
    UNASSIGNED_BUG,
    UNASSIGNED_STORY,

}
