package commands.enums;

public enum CommandType {

    LOGIN,
    LOGOUT,
    CREATE_NEW_MEMBER,
    SHOW_BOARD_ACTIVITY,
    SHOW_TEAM_BOARD,
    CREATE_NEW_BOARD,
    CHANGE_FEEDBACK_RATING,
    CREATE_NEW_BUG,
    CREATE_NEW_FEEDBACK,
    CREATE_NEW_STORY,
    CREATE_NEW_TEAM,
    SHOW_ALL_TEAMS,
    SHOW_MEMBER_ACTIVITY,
    SHOW_TEAM_MEMBERS,
    ADD_MEMBER_TO_TEAM,
    SHOW_ALL_MEMBERS,






}
